### ISSUE TITLE
Chart.redraw() throws "Uncaught TypeError: oldData[i].update is not a function"

### ISSUE THREAD

**Issue by aliekens** [highslide-software/highcharts.com#4150]
Upon updating the various series of a stacked bargraph with `setData( ..., false )` (so it is not redrawn until all series have been set) and consequently requesting a `chart.redraw();` an `Uncaught TypeError: oldData[i].update is not a function` error is thrown.

I don't have a complete jsfiddle, the relevant code is as follows:

```js
// add new data to chart, without redrawing
arr.timelinedata.forEach( function( data ) {
  chart.series[ parseInt( data.name ) ].setData( data.data, false );
});
// redraw
chart.redraw();
```

This issue is not present in version 3.0.9 of Highcharts and appeared with version 3.0.10.

**Comment by pawelfus** [comment]
Works fine in 4.1.6: http://jsfiddle.net/v9n41j2h/

**Comment by pawelfus** [comment]
Works also with different length for datasets: http://jsfiddle.net/v9n41j2h/1/
