### ISSUE TITLE
Highstock: setting xAxis range larger that data set breaks chart

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4501]
Setting xAxis range larger than time span of data use in chart via rangeSelector buttons causes errors:
`highstock.src.js:2931 Error: Invalid value for <rect> attribute width="NaN"`
`highstock.src.js:2931 Error: Invalid value for <rect> attribute x="NaN"`
Example: http://jsfiddle.net/27vapLwa/
Steps: 
1) click '9y' button
2) click '10y' button
Errors in console and chart is broken

A similar problem is visible when using demo from API reference:
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/rangeselector/allbuttonsenabled-true/
Steps: click '1y' button (the chart is broken, but no errors)

Both are working with Highstock 2.1.7

**Comment by pawelfus** [comment]
Broken since [this commit](https://github.com/highslide-software/highcharts.com/commit/b40468d).
